import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "./Header";
import Menu from "@/components/menu";
import { preah } from "@/components/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vcrap - Shopping Scraper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={preah.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <div className="flex dark:bg-slate-950 min-h-[88lvh]">
            <Menu />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
